define({
  root: {
    labelBookmarkName: "Bookmark the current view",
    labelPlay: "Play All",
    labelStop: "Stop",
    labelDelete: "Delete",
    placeholderBookmarkName: "Bookmark Name",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!"
  },
  "ar": true,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": true,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-BR": true,
  "pt-PT": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});